project:
  type: website
  output-dir: docs
website:
  open-graph: true
  navbar:
    search: true
    title: "Naveen Kannan"
    href: about.qmd
    background: primary
    left:
      - text: "About"
        file: about.qmd
      - text: "Publications"
        file: publications.qmd
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "Blog Posts"
        file: blog_main.qmd
    right:
      - icon: github
        href: https://github.com/naveenk2022
      - icon: linkedin
        href: https://www.linkedin.com/in/naveenkannan1/
      - icon: file-person
        text: CV
        href: https://github.com/naveenk2022/data_resume/blob/main/resume.pdf

      
format:
  html:
    theme: 
      light: [flatly, light.scss]
      dark: [darkly, dark.scss]
    css: styles.css
    toc: true

editor: visual
execute:
  freeze: auto
