{
  "hash": "7be559183408311eb34545ce1d89ef25",
  "result": {
    "markdown": "---\ntitle: \"Analysing the relationship between Blood Cholesterol levels, Physical Activity, Excessive Drinking and Depression. \"\nauthor: \"Naveen Kannan\"\ndate: 2022-12-14\nformat: \n  html:\n    toc: true\n    number-sections: true\n    code-fold: show\n    code-tools: true\n    code-overflow: wrap\n    date-format: iso\n---\n\n\n# Setup and Data Ingest\n\n## Loading Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsource(\"Love-boost.R\")\n\nlibrary(knitr)\nlibrary(rmdformats)\nlibrary(nhanesA)\nlibrary(kableExtra)\nlibrary(naniar)\nlibrary(janitor)\nlibrary(glue)\nlibrary(rcompanion)\nlibrary(gt)\nlibrary(ggridges)\nlibrary(patchwork)\nlibrary(broom)\nlibrary(tidyverse)\n\n## Global options\noptions(max.print=\"100\")\nopts_chunk$set(comment=NA)\nopts_knit$set(width=75)\nknitr::opts_chunk$set(comment = NA)\n```\n:::\n\n\n## Ingesting Data\n\nThe `nhanes` package was used to read the data and store in in the form of an .Rds file for each of the data sets being used.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Demographic Data\n#demo_raw <- nhanes('P_DEMO') |> tibble()\n#saveRDS(demo_raw, \"C:\\\\Users\\\\navee\\\\Desktop\\\\PQHS 431\\\\Project B\\\\data\\\\P_DEMO.Rds\")\ndemo_raw <- readRDS(\"data/P_DEMO.Rds\")\n\n## Alcohol Data\n#alc_raw <- nhanes('P_ALQ') |> tibble()\n#saveRDS(alc_raw, \"C:\\\\Users\\\\navee\\\\Desktop\\\\PQHS 431\\\\Project B\\\\data\\\\P_ALQ.Rds\")\nalc_raw <- readRDS(\"data/P_ALQ.Rds\")\n\n## Depression data\n#depr_raw <- nhanes('P_DPQ') |> tibble()\n#saveRDS(depr_raw, \"C:\\\\Users\\\\navee\\\\Desktop\\\\PQHS 431\\\\Project B\\\\data\\\\P_DPQ.Rds\")\ndepr_raw <- readRDS(\"data/P_DPQ.Rds\")\n\n## Physical activity data\n#phys_raw <- nhanes('P_PAQ') |> tibble()\n#saveRDS(phys_raw, \"C:\\\\Users\\\\navee\\\\Desktop\\\\PQHS 431\\\\Project B\\\\data\\\\P_PAQ.Rds\")\nphys_raw <- readRDS(\"data/P_PAQ.Rds\")\n\n## Cholesterol data\n#chol_raw <- nhanes('P_HDL') |> tibble()\n#saveRDS(chol_raw, \"C:\\\\Users\\\\navee\\\\Desktop\\\\PQHS 431\\\\Project B\\\\data\\\\P_HDL.Rds\")\nchol_raw <- readRDS(\"data/P_HDL.Rds\")\n```\n:::\n\n\nThe tibbles were then merged on the `SEQN` variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Merging the tibbles\nNEW <- left_join(demo_raw, chol_raw, by = \"SEQN\")\nNEW2 <- left_join(NEW, alc_raw, by = \"SEQN\")\nNEW3 <- left_join(NEW2, depr_raw, by = \"SEQN\")\ncombined_tib <- left_join(NEW3, phys_raw, by = \"SEQN\")\n```\n:::\n\n\n# Cleaning the Data\n\nMissing values, values such as \"Refused\", or \"Don't Know\", were filtered out, and participants from 21 to 79 years of age were selected.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfinal_tib <- combined_tib|>\n  filter(RIDSTATR == 2) |>\n  filter(RIDAGEYR > 20 &  RIDAGEYR < 80) |>\n  filter(PAD680 !=7777 & PAD680 != 9999 &\n         PAD675 != 7777 & PAD675 != 9999 &\n         PAQ650 != 7 & PAQ650 != 9 &\n         ALQ151 != 7 & ALQ151 !=9 &\n         DPQ020 != 7 & DPQ020 != 9 &\n         DPQ050 != 7 & DPQ050 != 9 &\n         LBDHDD != \".\") |>\n  filter(complete.cases(LBDHDD,PAD680,PAD675,PAQ650,ALQ151,DPQ020,DPQ050))|>\n  mutate(PAQ650 = 2- PAQ650) |> \n  mutate(ALQ151 = 2- ALQ151) |>\n  mutate(PAQ650 = as.factor(PAQ650)) |>\n  mutate(ALQ151 = as.factor(ALQ151)) |>\n  mutate(DPQ020 = as.factor(DPQ020)) |>\n  mutate(DPQ050 = as.factor(DPQ050)) |>\n  select(SEQN,LBDHDD,PAD680,PAD675,PAQ650,ALQ151,DPQ020,DPQ050) \nfinal_tib\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2,657 × 8\n     SEQN LBDHDD PAD680 PAD675 PAQ650 ALQ151 DPQ020 DPQ050\n    <dbl>  <dbl>  <dbl>  <dbl> <fct>  <fct>  <fct>  <fct> \n 1 109266     56    480     30 1      0      0      0     \n 2 109273     42    180    120 0      0      2      2     \n 3 109274     29    300     60 0      0      0      0     \n 4 109290     40    180     90 0      0      1      0     \n 5 109312     77    180    120 0      0      0      0     \n 6 109313     54    300     60 1      0      0      0     \n 7 109317     71    420     30 0      0      1      2     \n 8 109319    110    600     60 1      0      0      0     \n 9 109324     60    360     20 0      0      1      0     \n10 109327     58    480     30 1      0      0      0     \n# ℹ 2,647 more rows\n```\n:::\n:::\n\n\n# Codebook and Data Description\n\n**2,657 adults ages 21-79 participating in NHANES 2017-18 with complete data on the variables listed in the table below.**\n\n| Variable name | Variable Type               | Description                                                                                                                                                                                                                                         | Analytic Role                |\n|--------------|--------------|--------------------------------|--------------|\n| `SEQN`        | \\-                          | Respondent sequence number **(Unique Identifier)**                                                                                                                                                                                                  | Indexing                     |\n| `LBDHDD`      | Continuous variable         | Direct HDL-Cholesterol **(mg/dL)**                                                                                                                                                                                                                  | Outcome variable             |\n| `PAD680`      | Continuous variable         | Time spent sitting on a typical day **(Minutes)**                                                                                                                                                                                                   | Quantitative predictor       |\n| `PAD675`      | Continuous variable         | Time spent performing moderate-intensity sports, fitness or recreational activities on a typical day **(Minutes)**                                                                                                                                  | Quantitative Predictor       |\n| `PAQ650`      | Binary categorical variable | Whether or not the participant performs any vigorous-intensity sports, fitness, or recreational activities that cause large increases in breathing or heart rate like running or basketball for at least 10 minutes continuously, in a typical week | Binary categorical predictor |\n| `ALQ151`      | Binary categorical variable | Whether or not the participant had a period in their life where they drank 4 or more drinks of any alcoholic beverage almost every day                                                                                                              | Binary categorical predictor |\n| `DPQ020`      | Multi-categorical variable  | Over the last 2 weeks, how often has the participant been bothered by the following problems: feeling down, depressed, or hopeless                                                                                                                  | Multi-categorical predictor  |\n| `DPQ050`      | Multi-categorical variable  | Over the last 2 weeks, how often has the participant been bothered by the following problems: poor appetite or overeating                                                                                                                           | Multi-categorical predictor  |\n\n**The levels of the categorical variables under study and their descriptions are as follows:**\n\n| Variable name | Original Levels                                                                                                            | New levels                                                                                     | Variable description                                                                                                                                                                                                                                |\n|---------------|--------------------|---------------|----------------------|\n| `PAQ650`      | 4 levels: 1 = Yes, 2 = No, 7 = Refused, 9 = Don't Know                                                                     | 2 levels: 1 = Yes, 0 = No                                                                      | Whether or not the participant performs any vigorous-intensity sports, fitness, or recreational activities that cause large increases in breathing or heart rate like running or basketball for at least 10 minutes continuously, in a typical week |\n| `ALQ151`      | 4 levels: 1 = Yes, 2 = No, 7 = Refused, 9 = Don't Know                                                                     | 2 levels: 1 = Yes, 0 = No                                                                      | Whether or not the participant had a period in their life where they drank 4 or more drinks of any alcoholic beverage almost every day                                                                                                              |\n| `DPQ020`      | 6 levels: 0 = Not at all, 1 = Several days, 2 = More than half the days, 3 = Nearly every day, 7 = refused, 9 = Don't know | 4 levels : 0 = Not at all, 1 = Several days, 2 = More than half the days, 3 = Nearly every day | Over the last 2 weeks, how often has the participant been bothered by the following problems: feeling down, depressed, or hopeless                                                                                                                  |\n| `DPQ050`      | 6 levels: 0 = Not at all, 1 = Several days, 2 = More than half the days, 3 = Nearly every day, 7 = refused, 9 = Don't know | 4 levels : 0 = Not at all, 1 = Several days, 2 = More than half the days, 3 = Nearly every day | Over the last 2 weeks, how often has the participant been bothered by the following problems: poor appetite or overeating                                                                                                                           |\n\n# Analysis B : Comparing 2 Means with Independent Samples\n\n## The Question\n\n**Among adults of ages 21-79 participating in NHANES 2017-18, is there a significant difference in the values of HDL cholesterol values of participants across their self-reported participation or lack thereof in vigorous weekly physical activity?**\n\n## Describing the Data\n\n**The Outcome Variable**\n\nThe outcome variable is `LBDHDD`, which is a *continuous quantitative variable*. It describes the Direct HDL-Cholesterol levels of the participants in **mg/dL(milligrams of HDL-Cholesterol per deciliter of blood).** The values range from 5 to 189 mg/dL, from the documentation of the variable available at https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/P_HDL.htm#LBDHDD.\n\n**The Binary Categorical Exposure Variable**\n\nThe categorical variable is `PAQ650`, which is a **Binary Categorical Variable**. It describes whether or not the participant performs any vigorous-intensity sports, fitness, or recreational activities that cause large increases in breathing or heart rate like running or basketball for at least 10 minutes continuously, in a typical week. It has the following factors :\n\n\"1\" - Yes \"0\" - No\n\nThe samples here are independent, as the levels of the exposure variable `PAQ650` are mutually exclusive and exhaustive, with only 1 of two possible answers that can apply to each participant.\n\n### Numerical Summary of Direct HDL- Cholesterol across weekly vigorous activity groups\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmosaic::favstats(LBDHDD ~ PAQ650, data = final_tib) |>\n  kable(digits = 2) |> \n  kable_classic_2(font_size = 28, full_width = F)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\" lightable-classic-2\" style='font-size: 28px; font-family: \"Arial Narrow\", \"Source Sans Pro\", sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> PAQ650 </th>\n   <th style=\"text-align:right;\"> min </th>\n   <th style=\"text-align:right;\"> Q1 </th>\n   <th style=\"text-align:right;\"> median </th>\n   <th style=\"text-align:right;\"> Q3 </th>\n   <th style=\"text-align:right;\"> max </th>\n   <th style=\"text-align:right;\"> mean </th>\n   <th style=\"text-align:right;\"> sd </th>\n   <th style=\"text-align:right;\"> n </th>\n   <th style=\"text-align:right;\"> missing </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> 0 </td>\n   <td style=\"text-align:right;\"> 23 </td>\n   <td style=\"text-align:right;\"> 42 </td>\n   <td style=\"text-align:right;\"> 51 </td>\n   <td style=\"text-align:right;\"> 62 </td>\n   <td style=\"text-align:right;\"> 138 </td>\n   <td style=\"text-align:right;\"> 53.42 </td>\n   <td style=\"text-align:right;\"> 15.57 </td>\n   <td style=\"text-align:right;\"> 1492 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:right;\"> 10 </td>\n   <td style=\"text-align:right;\"> 44 </td>\n   <td style=\"text-align:right;\"> 53 </td>\n   <td style=\"text-align:right;\"> 65 </td>\n   <td style=\"text-align:right;\"> 166 </td>\n   <td style=\"text-align:right;\"> 55.96 </td>\n   <td style=\"text-align:right;\"> 16.90 </td>\n   <td style=\"text-align:right;\"> 1165 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nThe numerical summary indicates that there are differences in the distribution of the outcome variable across the vigorous activity groups. The range of HDL cholesterol goes to a higher level in the group that answered yes, and the mean and median HDL levels in the group are higher than that of the group that answered no, although it is yet to be seen if this difference is statistically meaningful. Furthermore, 1492 participants answered no, while 1165 participants answered yes, indicating that the study design is imbalanced.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntemp1 <- final_tib |> \n  mutate(PAQ650_f = fct_recode(factor(PAQ650),\n                              \"No vigorous weekly physical activity\" = \"0\",\n                              \"Atleast once per week\" = \"1\")) |> \n    select(PAQ650_f,LBDHDD)\nggplot(temp1, aes(x = LBDHDD, y = PAQ650_f, fill = PAQ650_f, height = after_stat(density))) +\n    ggridges::geom_density_ridges(scale = 2) +\n    scale_fill_brewer(palette = \"Blues\") +\n    guides(fill = \"none\") +\n    labs(title = str_wrap(\"Direct HDL-Cholesterol levels of participants split according to their self-reported participation in vigorous weekly physical activity\", width = 70),\n         x = \"Direct HDL-Cholesterol (mg/dL)\",\n         y = \"Self reported participation in weekly vigorous physical activity\",\n       subtitle = str_wrap(glue(\"Across \", nrow(temp1), \n                           \" participants from NHANES 2017-18 data with complete data. \"), width = 70),\n       caption = \"Source: NHANES 2017-18.\") \n```\n\n::: {.cell-output .cell-output-stderr}\n```\nPicking joint bandwidth of 3.28\n```\n:::\n\n::: {.cell-output-display}\n![](Study-1_files/figure-html/unnamed-chunk-4-1.png){width=768}\n:::\n:::\n\n\nVisualizing the levels of direct HDL-cholesterol among study participants across weekly exercise activity shows that there is a difference in HDL-cholesterol levels, albeit slight. Individuals who participate in vigorous physical activity atleast once a week appear to have higher HDL-cholesterol levels than individuals who do not participate in weekly vigorous physical activity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- \n  ggplot(temp1, aes(x = LBDHDD)) +\n  geom_histogram(bins = 20, \n  fill = \"#2b8cbe\", col = \"white\") +\n  facet_grid(PAQ650_f ~ ., labeller = 'label_value') +\n  labs( x = \"Direct HDL-Cholesterol (mg/dL)\", y = \"\")\n\np2 <- \n  ggplot(temp1, aes(sample = LBDHDD)) + \n  geom_qq(col = \"#2b8cbe\") + geom_qq_line(col = \"red\") +\n  facet_grid(PAQ650_f ~ ., labeller = 'label_value') +\n  labs(x = \"\", y = \"Direct HDL-Cholesterol (mg/dL)\")\n\np3 <- \n  ggplot(temp1, aes(x = \"\", y = LBDHDD)) +\n  geom_violin(fill = \"#2b8cbe\", alpha = 0.3) + \n  geom_boxplot(fill = \"#2b8cbe\", width = 0.3,\n               outlier.color = \"red\") +\n  facet_grid(PAQ650_f ~ ., labeller = 'label_value') +\n  labs(y = \"Direct HDL-Cholesterol (mg/dL)\", x = \"\") + coord_flip()\n\np2 + p1 - p3 +\n  plot_layout(ncol = 1, height = c(3, 2)) + \n  plot_annotation(title = str_wrap(\"Distribution of Direct HDL-Cholesterol (mg/dL), split according to the self reported weekly vigorous physical activity of the participant\", width = 100),\n         subtitle = glue(\"Across \", nrow(temp1), \n                           \" participants. Data taken from NHANES 2017-18\"))\n```\n\n::: {.cell-output-display}\n![](Study-1_files/figure-html/unnamed-chunk-5-1.png){width=768}\n:::\n:::\n\n\nThe distribution of Direct HDL-Cholesterol values across the two different groups of weekly vigorous activity demonstrates that the distribution has a significant right skew, from the shape of the Q-Q plots, the shape of the histogram, and the outliers detected in the boxplot and violinplot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfinal_tib |>\n  summarise(mean(LBDHDD), median(LBDHDD), sd(LBDHDD),\n              skew1 = (mean(LBDHDD) - median(LBDHDD))/sd(LBDHDD)) |>\n    kbl(digits = 2) |>kable_classic_2(font_size = 28, full_width = F)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\" lightable-classic-2\" style='font-size: 28px; font-family: \"Arial Narrow\", \"Source Sans Pro\", sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> mean(LBDHDD) </th>\n   <th style=\"text-align:right;\"> median(LBDHDD) </th>\n   <th style=\"text-align:right;\"> sd(LBDHDD) </th>\n   <th style=\"text-align:right;\"> skew1 </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 54.53 </td>\n   <td style=\"text-align:right;\"> 52 </td>\n   <td style=\"text-align:right;\"> 16.21 </td>\n   <td style=\"text-align:right;\"> 0.16 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nThe numerical value of the skew also indicates that the data is right-skewed. From the data visualization and the numerical summaries, the right-skewed, non-normal distribution of the outcome variable indicates that the bootstrap method is ideal in order to *compare the difference in means across the two groups.*\n\n## Main Analysis\n\nGiven the non-normality of the outcome variable's distribution and the imbalance in the study design, the Bootstrap method would be the ideal choice to estimate the difference in means across the two groups. After setting a seed, the `bootdif` function from the love-boost script was used to perform a bootstrapped analysis of the difference in mean HDL levels between the weekly vigorous exercise groups.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(4312022)\n\nbootdif(final_tib$LBDHDD, final_tib$PAQ650, conf.level = 0.90)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMean Difference            0.05            0.95 \n       2.545718        1.491790        3.637311 \n```\n:::\n:::\n\n\n## Conclusions\n\nThe 90% confidence interval for the difference in the means of Direct HDL-Cholesterol levels goes from 1.49 mg/dL to 3.64 mg/dL, which are a reasonable range of estimates for the true difference of the mean of Direct HDL-Cholesterol levels across the two weekly vigorous activity groups. The point estimate of the difference in means is 2.55 mg/dL. This confidence interval *does not include zero.*\n\nFrom the fact that we are using a 90% confidence interval, we can be 90% sure that this method of creating a confidence interval will produce a result containing the true difference in means. *(This means that if bootstrapping was done 100 times to create 100 different intervals, 90 of those intervals will have the true difference in mean Direct HDL-Cholesterol levels.)*\n\n**There is a statistically detectable difference in Direct HDL-Cholesterol levels across the two groups of weekly vigorous physical activity.**\n\n**The mean blood HDL cholesterol for individuals who reported weekly vigorous physical activity was 2.55 mg/dL higher than that of individuals who did not report weekly vigorous physical activity, with a 90% CI of (1.49, 3.64 mg/dL).**\n\nHowever, while there is a statistical difference, the mean difference varies from 1.49 to 3.64 mg/dL. This difference may not be medically significant.\n\n# Analysis C - Comparing 3+ Population Means via ANOVA\n\n## The Question\n\n**Among adults of ages 21-79 participating in NHANES 2017-18, are differences in severity of feeling down, depressed, or hopeless associated with differences in the number of minutes of daily sedentary activity among NHANES 2017-18 participants?**\n\n## Describing the Data\n\n**The Outcome Variable**\n\nThe outcome variable is `PAD680`, which is a *continuous quantitative variable*. It describes the participants time spent sitting on a typical day in **Minutes**.\n\n**The Multi-Categorical Exposure Variable**\n\nThe categorical variable is `DPQ020`, which is a **Multi-Categorical Variable**. It describes how often has the participant been bothered by the following problems: feeling down, depressed, or hopeless over the past 2 weeks. It has the following factors :\n\n4 levels :\n\n0 = Not at all\n\n1 = Several days\n\n2 = More than half the days\n\n3 = Nearly every day\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmosaic::favstats(PAD680 ~ DPQ020, data = final_tib) |> kbl() |> \n  kable_classic_2(font_size = 28)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\" lightable-classic-2\" style='font-size: 28px; font-family: \"Arial Narrow\", \"Source Sans Pro\", sans-serif; margin-left: auto; margin-right: auto;'>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> DPQ020 </th>\n   <th style=\"text-align:right;\"> min </th>\n   <th style=\"text-align:right;\"> Q1 </th>\n   <th style=\"text-align:right;\"> median </th>\n   <th style=\"text-align:right;\"> Q3 </th>\n   <th style=\"text-align:right;\"> max </th>\n   <th style=\"text-align:right;\"> mean </th>\n   <th style=\"text-align:right;\"> sd </th>\n   <th style=\"text-align:right;\"> n </th>\n   <th style=\"text-align:right;\"> missing </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> 0 </td>\n   <td style=\"text-align:right;\"> 10 </td>\n   <td style=\"text-align:right;\"> 180 </td>\n   <td style=\"text-align:right;\"> 300 </td>\n   <td style=\"text-align:right;\"> 480 </td>\n   <td style=\"text-align:right;\"> 1080 </td>\n   <td style=\"text-align:right;\"> 336.9990 </td>\n   <td style=\"text-align:right;\"> 197.0243 </td>\n   <td style=\"text-align:right;\"> 2042 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 180 </td>\n   <td style=\"text-align:right;\"> 300 </td>\n   <td style=\"text-align:right;\"> 480 </td>\n   <td style=\"text-align:right;\"> 960 </td>\n   <td style=\"text-align:right;\"> 331.5556 </td>\n   <td style=\"text-align:right;\"> 196.0190 </td>\n   <td style=\"text-align:right;\"> 450 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:right;\"> 20 </td>\n   <td style=\"text-align:right;\"> 180 </td>\n   <td style=\"text-align:right;\"> 240 </td>\n   <td style=\"text-align:right;\"> 360 </td>\n   <td style=\"text-align:right;\"> 900 </td>\n   <td style=\"text-align:right;\"> 294.8454 </td>\n   <td style=\"text-align:right;\"> 186.7324 </td>\n   <td style=\"text-align:right;\"> 97 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:right;\"> 15 </td>\n   <td style=\"text-align:right;\"> 120 </td>\n   <td style=\"text-align:right;\"> 300 </td>\n   <td style=\"text-align:right;\"> 420 </td>\n   <td style=\"text-align:right;\"> 960 </td>\n   <td style=\"text-align:right;\"> 301.4706 </td>\n   <td style=\"text-align:right;\"> 208.0203 </td>\n   <td style=\"text-align:right;\"> 68 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nThe above table depicts the summary statistics of `PAD680` values across the levels of `DPQ020`. From the summary statistics alone, there appears to be a differences in the mean `PAD680` value across the different levels of `DPQ020`. However, numbers alone are not enough to make any conclusions, and the data needs to be visualized.\n\nUsing ggplot and ggridges, the distribution of `PAD680` values across the levels of `DPQ020` was visualized, and given a color scale to help the different categories stand out visually.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntemp2 <- final_tib |> \n  mutate(DPQ020_f = fct_recode(factor(DPQ020),\n                              \"Not at all\" = \"0\",\n                              \"Several days\" = \"1\",\n                              \"More than half the days\" = \"2\",\n                              \"Nearly every day\" = \"3\")) |> \n    select(DPQ020_f,PAD680)\nggplot(temp2, aes(x = PAD680, y = DPQ020_f, fill = DPQ020_f, height = after_stat(density))) +\n    ggridges::geom_density_ridges(scale = 2) +\n    scale_fill_brewer(palette = \"RdYlGn\", direction = -1) +\n    guides(fill = \"none\") +\n    labs(title = str_wrap(\"Minutes of sedentary activity of NHANES participants per day split according to how often they felt down, depressed or hopeless over the past 2 weeks.\", width = 70),\n         x = \"Minutes of sedentary activity during the day (Minutes)\",\n         y = str_wrap(\"How often did the participant feel down, depressed or hopeless over the past 2 weeks?\",width = 70),\n       subtitle = str_wrap(glue(\"Across \", nrow(temp2), \n                           \" participants from NHANES 2017-18 data with complete data. \"), width = 70),\n       caption = \"Source: NHANES 2017-18.\") \n```\n\n::: {.cell-output .cell-output-stderr}\n```\nPicking joint bandwidth of 54.9\n```\n:::\n\n::: {.cell-output-display}\n![](Study-1_files/figure-html/unnamed-chunk-9-1.png){width=768}\n:::\n:::\n\n\nThe above graphic visualizes the distribution of `DPQ020` *(Minutes of sedentary activity of NHANES participants per day)* according to the `PAD680` *(How often did the participant feel down, depressed or hopeless over the past 2 weeks?)* category of the participant. From looking at the plot, it does appear that categories 2 (More than half the days) and 3 (Nearly every day) have a larger proportion of minutes of sedentary activity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(temp2, aes(x = PAD680, y = DPQ020_f, fill = DPQ020_f)) +\n  geom_violin(alpha = 0.3) +\n  geom_boxplot(width = 0.3) +\n  scale_fill_brewer(palette = \"RdYlGn\", direction = -1) +\n  coord_flip() +\n  guides(fill = \"none\") +\n  theme_bw() +\n  labs(title = str_wrap(\"Minutes of sedentary activity of NHANES participants per day split according to how often they felt down, depressed or hopeless over the past 2 weeks.\", width = 70),\n       y = str_wrap(\"How often did the participant feel down, depressed or hopeless over the past 2 weeks?\",width = 70),\n       x = \"Minutes of sedentary activity per day\",\n       caption = \"Data taken from NHANES 2017-18\")\n```\n\n::: {.cell-output-display}\n![](Study-1_files/figure-html/unnamed-chunk-10-1.png){width=768}\n:::\n:::\n\n\nThe above plot demonstrates the variance of `PAD680` values across the 4 categories of `DPQ020`. `PAD680` appears to have more or less equal variance across the 4 categories.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- \n  ggplot(temp2, aes(x = PAD680)) +\n  geom_histogram(bins = 20, \n  fill = \"#2b8cbe\", col = \"white\") +\n  facet_grid(DPQ020_f ~ ., labeller = 'label_value') +\n  labs( x = \"Minutes of sedentary activity during the day (Minutes)\", y = \"\")\n\np2 <- \n  ggplot(temp2, aes(sample = PAD680)) + \n  geom_qq(col = \"#2b8cbe\") + geom_qq_line(col = \"red\") +\n  facet_grid(DPQ020_f ~ ., labeller = 'label_value') +\n  labs(x = \"\", y = \"Minutes of sedentary activity during the day (Minutes)\")\n\np3 <- \n  ggplot(temp2, aes(x = \"\", y = PAD680)) +\n  geom_violin(fill = \"#2b8cbe\", alpha = 0.3) + \n  geom_boxplot(fill = \"#2b8cbe\", width = 0.3,\n               outlier.color = \"red\") +\n  facet_grid(DPQ020_f ~ ., labeller = 'label_value') +\n  labs(y = \"Minutes of sedentary activity during the day (Minutes)\", x = \"\") + coord_flip()\n\np2 + p1 - p3 +\n  plot_layout(ncol = 1, height = c(3, 2)) + \n  plot_annotation(title = str_wrap(\"Distribution of Minutes of Sedentary Activity of NHANES participants per day\", width = 90),\n         subtitle = str_wrap(glue(\"Across \", nrow(temp2), \n                           \" participants, split according to how often they felt down, depressed or hopeless over the past 2 weeks. Data taken from NHANES 2017-18.\"), width = 90))\n```\n\n::: {.cell-output-display}\n![](Study-1_files/figure-html/unnamed-chunk-11-1.png){width=768}\n:::\n:::\n\n\nThese plots demonstrate the distribution of `PAD680`. The distribution is skewed to the right, and does not appear to have a normal distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfinal_tib |>\n  summarise(mean(PAD680), median(PAD680), sd(PAD680),\n              skew1 = (mean(PAD680) - median(PAD680))/sd(PAD680)) |>\n    kbl(digits = 2) |>kable_classic_2(font_size = 28, full_width = F)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\" lightable-classic-2\" style='font-size: 28px; font-family: \"Arial Narrow\", \"Source Sans Pro\", sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> mean(PAD680) </th>\n   <th style=\"text-align:right;\"> median(PAD680) </th>\n   <th style=\"text-align:right;\"> sd(PAD680) </th>\n   <th style=\"text-align:right;\"> skew1 </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 333.63 </td>\n   <td style=\"text-align:right;\"> 300 </td>\n   <td style=\"text-align:right;\"> 196.9 </td>\n   <td style=\"text-align:right;\"> 0.17 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nThe numerical summaries also demonstrate the `PAD680` does not have a normal distribution; it is right-skewed. There is a marked difference between the mean and the median, and the numerical value of the skew also demonstrates a right skew.\n\n## Main Analysis\n\nGiven that `PAD680` does not have a normal distribution, even though the distribution of `PAD680` across `DPQ020` has equal variance, the assumptions of an ANOVA test would be violated if it were to be performed on these two variables.\n\nThe three main assumptions of an ANOVA test are as follows.\n\n1.  **Normality**\n\n*Each sample was drawn from a normally distributed population.*\n\n2.  **Equal variance**\n\n*The variances of the populations that the samples come from are equal.*\n\n3.  **Independence**\n\n*The observations in each group are independent of each other and the observations within groups were obtained by a random sample.*\n\nThus, the Kruskal-Wallis rank sum test would be preferable to the ANOVA test to estimate if there is a significant difference in the mean value of `PAD680` across the 4 categories of `DPQ020`, especially because of the significant right-skew of the data. The Kruskal-Wallis test is *non-parametric*, which means that it does not need any distributional assumption.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkruskal.test(PAD680 ~ DPQ020, data = final_tib)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  PAD680 by DPQ020\nKruskal-Wallis chi-squared = 6.7478, df = 3, p-value = 0.08038\n```\n:::\n:::\n\n\nThe results of the Kruskal-Wallis test do not indicate a meaningful difference in the values of `PAD680` across the levels of `DPQ020`, given that the p value is 0.080, with a significance value of 0.05.\n\n## Conclusions\n\n**From the results of the Kruskal-Wallis test, among the study population taken from NHANES 2017-18, there is no statistically detectable difference in the number of minutes of daily sedentary activity across the different levels of how often they felt down, depressed or hopeless over the past 2 weeks.**\n\n# Analysis D - Analyzing a 2x2 table\n\n## The Question\n\n**Among adults of ages 21-79 participating in NHANES 2017-18, is there an association between a period of heavy drinking (described as having 4 or more alcoholic beverages daily) and a lack of weekly vigorous physical activity?**\n\n## Describing the Data\n\nThe two binary categorical variables under study are:\n\n**The Outcome Variable**\n\n`PAQ650` - It describes whether or not the participant performs any vigorous-intensity sports, fitness, or recreational activities that cause large increases in breathing or heart rate like running or basketball for at least 10 minutes continuously, in a typical week. It has the following levels:\n\n1 = Yes\n\n0 = No\n\n**The Exposure Variable**\n\n`ALQ151` - It describes whether or not the participant had a period in their life where they drank 4 or more drinks of any alcoholic beverage almost every day. It has the following levels:\n\n1 = Yes\n\n0 = No\n\nUsing the mutate function, the variables `ALQ151` and `PAQ650` were given different factor names to aid in understanding their meaning.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntemp3<- final_tib |>\n  mutate(ALQ151 = fct_recode(factor(ALQ151),\n                                \"Yes\" = \"1\",\n                                \"No\" = \"0\"),\n         PAQ650 = fct_recode(factor(PAQ650),\n                                \"Yes\" = \"1\",\n                                \"No\" = \"0\")) |>\n  select(PAQ650, ALQ151)\n\ntemp3 <- temp3 |>\n  mutate(ALQ151 = fct_relevel(ALQ151, \"Yes\"),\n         PAQ650 = fct_relevel(PAQ650, \"No\", \"Yes\"))\n```\n:::\n\n\nThe tabyl function was used to create a table of the two variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable3 <- temp3 |> tabyl(ALQ151, PAQ650)|> \n    adorn_totals(where = c(\"row\")) |>\n    adorn_percentages(denominator = \"row\") |>\n    adorn_pct_formatting() |>\n    adorn_ns(position = \"front\")\n```\n:::\n\n\nUsing the `gt` package in conjunction with the `glue` package, a meaningful, visually appealing 2x2 table was created.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngt_table3 <- gt(table3)\ngt_table3 <- gt_table3 |>\n  tab_header(\n    title = md(\"**Exploring the relationship between heavy drinking and a lack of weekly vigorous physical activity.**\"),\n    subtitle = glue(\"Across \", nrow(temp3), \n                           \" participants with complete data.\")\n  ) |>\n  tab_spanner(\n    label = \"Does the participant perform any vigorous-intensity activities that cause large increases in breathing or heart rate for at least 10 minutes continuously, in a typical week?\",\n    columns = c(Yes, No)\n  ) |>\n  cols_label(\"ALQ151\" = \"Did the participant have a period in their life where they drank 4 or more drinks of any alcoholic beverage almost every day?\") |>\n  cols_label(\"No\" = md(\"**No**\")) |>\n  cols_label(\"Yes\" = md(\"**Yes**\")) |>\n  tab_source_note(\n    source_note = md(\"**Source:** _National Health and Nutrition Examination Survey, 2017-2018_\")\n  )\ngt_table3\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"qmwnzrhydr\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#qmwnzrhydr table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#qmwnzrhydr thead, #qmwnzrhydr tbody, #qmwnzrhydr tfoot, #qmwnzrhydr tr, #qmwnzrhydr td, #qmwnzrhydr th {\n  border-style: none;\n}\n\n#qmwnzrhydr p {\n  margin: 0;\n  padding: 0;\n}\n\n#qmwnzrhydr .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#qmwnzrhydr .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#qmwnzrhydr .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#qmwnzrhydr .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#qmwnzrhydr .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qmwnzrhydr .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qmwnzrhydr .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qmwnzrhydr .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#qmwnzrhydr .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#qmwnzrhydr .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#qmwnzrhydr .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#qmwnzrhydr .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#qmwnzrhydr .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#qmwnzrhydr .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#qmwnzrhydr .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#qmwnzrhydr .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#qmwnzrhydr .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#qmwnzrhydr .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#qmwnzrhydr .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qmwnzrhydr .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#qmwnzrhydr .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#qmwnzrhydr .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#qmwnzrhydr .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qmwnzrhydr .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#qmwnzrhydr .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#qmwnzrhydr .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qmwnzrhydr .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qmwnzrhydr .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#qmwnzrhydr .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qmwnzrhydr .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#qmwnzrhydr .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qmwnzrhydr .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qmwnzrhydr .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qmwnzrhydr .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qmwnzrhydr .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qmwnzrhydr .gt_left {\n  text-align: left;\n}\n\n#qmwnzrhydr .gt_center {\n  text-align: center;\n}\n\n#qmwnzrhydr .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#qmwnzrhydr .gt_font_normal {\n  font-weight: normal;\n}\n\n#qmwnzrhydr .gt_font_bold {\n  font-weight: bold;\n}\n\n#qmwnzrhydr .gt_font_italic {\n  font-style: italic;\n}\n\n#qmwnzrhydr .gt_super {\n  font-size: 65%;\n}\n\n#qmwnzrhydr .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#qmwnzrhydr .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#qmwnzrhydr .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#qmwnzrhydr .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#qmwnzrhydr .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#qmwnzrhydr .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#qmwnzrhydr .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal\" style><strong>Exploring the relationship between heavy drinking and a lack of weekly vigorous physical activity.</strong></td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Across 2657 participants with complete data.</td>\n    </tr>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"Did the participant have a period in their life where they drank 4 or more drinks of any alcoholic beverage almost every day?\">Did the participant have a period in their life where they drank 4 or more drinks of any alcoholic beverage almost every day?</th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"Does the participant perform any vigorous-intensity activities that cause large increases in breathing or heart rate for at least 10 minutes continuously, in a typical week?\">\n        <span class=\"gt_column_spanner\">Does the participant perform any vigorous-intensity activities that cause large increases in breathing or heart rate for at least 10 minutes continuously, in a typical week?</span>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Yes&lt;/strong&gt;\"><strong>Yes</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;No&lt;/strong&gt;\"><strong>No</strong></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"ALQ151\" class=\"gt_row gt_center\">Yes</td>\n<td headers=\"Yes\" class=\"gt_row gt_right\">131 (37.9%)</td>\n<td headers=\"No\" class=\"gt_row gt_right\">215 (62.1%)</td></tr>\n    <tr><td headers=\"ALQ151\" class=\"gt_row gt_center\">No</td>\n<td headers=\"Yes\" class=\"gt_row gt_right\">1,034 (44.7%)</td>\n<td headers=\"No\" class=\"gt_row gt_right\">1,277 (55.3%)</td></tr>\n    <tr><td headers=\"ALQ151\" class=\"gt_row gt_center\">Total</td>\n<td headers=\"Yes\" class=\"gt_row gt_right\">1,165 (43.8%)</td>\n<td headers=\"No\" class=\"gt_row gt_right\">1,492 (56.2%)</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"3\"><strong>Source:</strong> <em>National Health and Nutrition Examination Survey, 2017-2018</em></td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n:::\n:::\n\n\n## Main Analysis\n\nUsing the twobytwo function from the love-boost script, an analysis of the two-by-two table was conducted.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntwobytwo(215+2, 131+2, 1277+2, 1034+2, \"Drank 4 or more alcoholic drinks daily\",\"Did not have such a period\",\"No weekly physical activity\",\"Had weekly physical activity\", conf.level = 0.90)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n2 by 2 table analysis: \n------------------------------------------------------ \nOutcome   : No weekly physical activity \nComparing : Drank 4 or more alcoholic drinks daily vs. Did not have such a period \n\n                                       No weekly physical activity\nDrank 4 or more alcoholic drinks daily                         217\nDid not have such a period                                    1279\n                                       Had weekly physical activity\nDrank 4 or more alcoholic drinks daily                          133\nDid not have such a period                                     1036\n                                          P(No weekly physical activity)\nDrank 4 or more alcoholic drinks daily                            0.6200\nDid not have such a period                                        0.5525\n                                       90% conf. interval\nDrank 4 or more alcoholic drinks daily    0.5765   0.6617\nDid not have such a period                0.5354   0.5694\n\n                                   90% conf. interval\n             Relative Risk: 1.1222    1.0407   1.2101\n         Sample Odds Ratio: 1.3216    1.0888   1.6041\nConditional MLE Odds Ratio: 1.3215    1.0822   1.6163\n    Probability difference: 0.0675    0.0209   0.1125\n\n             Exact P-value: 0.0179 \n        Asymptotic P-value: 0.0179 \n------------------------------------------------------\n```\n:::\n:::\n\n\n## Conclusions\n\n### The Relative Risk\n\n**Individuals who have had a period of their life where they drank 4 or more alcoholic drinks a day have a 1.12 times higher risk(90% CI-1.04 to 1.21) of having no weekly vigorous physical activity when compared to individuals who did not have such a period.**\n\n### The Odds Ratio\n\n**Individuals who do not report weekly vigorous physical activity have 1.32 times higher odds(90% CI-1.09 to 1.60) of having had a period in their lives where they drank 4 or more alcoholic drinks a day when compared to individuals who did report weekly vigorous physical activity.**\n\n### The Risk Difference\n\n**The difference between in the probability of having no weekly vigorous physical activity for individuals who have had a period of their life where they drank 4 or more alcoholic drinks versus individuals who did not have such a period is 0.068 (90% CI - 0.021 to 0.113).**\n\n# Analysis E - Two-Way (4 x 2) Contingency Table\n\n## The Question\n\n**Among adults of ages 21-79 participating in NHANES 2017-18, is there an association between having had a period of heavy drinking (described as having 4 or more alcoholic beverages daily) and symptoms of depression (how often has the participant been bothered by the following problems: feeling down, depressed, or hopeless)?**\n\n## Describing the Data\n\nUsing the mutate function, the variables under study and their factors were re-leveled and renamed in order to create context and meaning for the data.\n\nThe tabyl function was then used to create a dataset containing the different factors of `DPQ020` as the rows, and the two factors of `ALQ151` as the columns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntemp4 <- final_tib |>\n  select(DPQ020, ALQ151) |>\n  mutate(DPQ020 = fct_recode(factor(DPQ020),\n                               \"Not at all\" = \"0\",\n                               \"Several Days\" = \"1\",\n                               \"More than half the days\" = \"2\",\n                               \"Nearly every day\" = \"3\"),\n         ALQ151 = fct_recode(factor(ALQ151),\n                               \"No\" = \"0\",\n                               \"Yes\" = \"1\"))\ntable4 <- temp4 |>\n  tabyl(DPQ020, ALQ151)|>\n  adorn_totals(where = c(\"row\")) |>\n    adorn_percentages(denominator = \"row\") |>\n    adorn_pct_formatting() |>\n    adorn_ns(position = \"front\")\n```\n:::\n\n\nThe `gt` package was used to create a meaningful, visually appealing table for the data present in `table4`, in conjunction with the `glue` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngt_table4 <- gt(table4)\ngt_table4 <- gt_table4 |>\n  tab_header(\n    title = md(\"**Exploring the relationship between depression and excessive drinking.**\"),\n    subtitle = glue(\"Across \", nrow(temp4), \n                           \" participants with complete data.\")\n  )|>\n  tab_spanner(\n    label = \"Did the participant have a period in their life where they drank 4 or more drinks of any alcoholic beverage almost every day?\",\n    columns = c(Yes, No)\n  ) |>\n  cols_label(\"DPQ020\" = \"Over the last 2 weeks, how often has the participant been bothered by the following problems: feeling down, depressed, or hopeless\") |>\n  cols_label(\"Yes\" = md(\"**Yes**\")) |>\n  cols_label(\"No\" = md(\"**No**\")) |>\n  tab_source_note(\n    source_note = md(\"**Source:** _National Health and Nutrition Examination Survey, 2017-2018_\")\n  )\ngt_table4\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"hajzjilrza\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#hajzjilrza table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#hajzjilrza thead, #hajzjilrza tbody, #hajzjilrza tfoot, #hajzjilrza tr, #hajzjilrza td, #hajzjilrza th {\n  border-style: none;\n}\n\n#hajzjilrza p {\n  margin: 0;\n  padding: 0;\n}\n\n#hajzjilrza .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#hajzjilrza .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#hajzjilrza .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#hajzjilrza .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#hajzjilrza .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hajzjilrza .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hajzjilrza .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hajzjilrza .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#hajzjilrza .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#hajzjilrza .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#hajzjilrza .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#hajzjilrza .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#hajzjilrza .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#hajzjilrza .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#hajzjilrza .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hajzjilrza .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#hajzjilrza .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#hajzjilrza .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#hajzjilrza .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hajzjilrza .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#hajzjilrza .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#hajzjilrza .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#hajzjilrza .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hajzjilrza .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#hajzjilrza .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#hajzjilrza .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hajzjilrza .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hajzjilrza .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#hajzjilrza .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hajzjilrza .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#hajzjilrza .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hajzjilrza .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hajzjilrza .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hajzjilrza .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hajzjilrza .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hajzjilrza .gt_left {\n  text-align: left;\n}\n\n#hajzjilrza .gt_center {\n  text-align: center;\n}\n\n#hajzjilrza .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#hajzjilrza .gt_font_normal {\n  font-weight: normal;\n}\n\n#hajzjilrza .gt_font_bold {\n  font-weight: bold;\n}\n\n#hajzjilrza .gt_font_italic {\n  font-style: italic;\n}\n\n#hajzjilrza .gt_super {\n  font-size: 65%;\n}\n\n#hajzjilrza .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#hajzjilrza .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#hajzjilrza .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#hajzjilrza .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#hajzjilrza .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#hajzjilrza .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#hajzjilrza .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal\" style><strong>Exploring the relationship between depression and excessive drinking.</strong></td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Across 2657 participants with complete data.</td>\n    </tr>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"Over the last 2 weeks, how often has the participant been bothered by the following problems: feeling down, depressed, or hopeless\">Over the last 2 weeks, how often has the participant been bothered by the following problems: feeling down, depressed, or hopeless</th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"Did the participant have a period in their life where they drank 4 or more drinks of any alcoholic beverage almost every day?\">\n        <span class=\"gt_column_spanner\">Did the participant have a period in their life where they drank 4 or more drinks of any alcoholic beverage almost every day?</span>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Yes&lt;/strong&gt;\"><strong>Yes</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;No&lt;/strong&gt;\"><strong>No</strong></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"DPQ020\" class=\"gt_row gt_center\">Not at all</td>\n<td headers=\"Yes\" class=\"gt_row gt_right\">238 (11.7%)</td>\n<td headers=\"No\" class=\"gt_row gt_right\">1,804 (88.3%)</td></tr>\n    <tr><td headers=\"DPQ020\" class=\"gt_row gt_center\">Several Days</td>\n<td headers=\"Yes\" class=\"gt_row gt_right\">67 (14.9%)</td>\n<td headers=\"No\" class=\"gt_row gt_right\">383 (85.1%)</td></tr>\n    <tr><td headers=\"DPQ020\" class=\"gt_row gt_center\">More than half the days</td>\n<td headers=\"Yes\" class=\"gt_row gt_right\">16 (16.5%)</td>\n<td headers=\"No\" class=\"gt_row gt_right\">81 (83.5%)</td></tr>\n    <tr><td headers=\"DPQ020\" class=\"gt_row gt_center\">Nearly every day</td>\n<td headers=\"Yes\" class=\"gt_row gt_right\">25 (36.8%)</td>\n<td headers=\"No\" class=\"gt_row gt_right\">43 (63.2%)</td></tr>\n    <tr><td headers=\"DPQ020\" class=\"gt_row gt_center\">Total</td>\n<td headers=\"Yes\" class=\"gt_row gt_right\">346 (13.0%)</td>\n<td headers=\"No\" class=\"gt_row gt_right\">2,311 (87.0%)</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"3\"><strong>Source:</strong> <em>National Health and Nutrition Examination Survey, 2017-2018</em></td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n:::\n:::\n\n\n## Main Analysis\n\nThe Pearson Chi-Square test of Independence was conducted to assess if there is an association between the rows and the columns of the contingency table.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable4a <- table(temp4$DPQ020, temp4$ALQ151)\nchisq.test(table4a)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test\n\ndata:  table4a\nX-squared = 39.629, df = 3, p-value = 1.277e-08\n```\n:::\n:::\n\n\nFrom the p-value of the above Chi-squared test, we can assume that there is a definite association between the rows and columns of the contingency table.\n\n**Cramer's V**\n\nFrom the Chi-squared test, we know that there is an association between the rows and the columns of the contingency table. However, to identify the *strength* of the association, the Cramer's V test, which is a test of statistical strength, can be conducted.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncramerV(table4a, ci = TRUE) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Cramer.V lower.ci upper.ci\n1   0.1221  0.07406   0.1801\n```\n:::\n:::\n\n\nThe point estimate of the Cramer's V value is 0.122, with 95% confidence intervals ranging from 0.074 to 0.180.\n\nFrom the Cramer's V test, given that there are 3 degrees of freedom, the association between depression and excessive drinking is not particularly strong, although it is definitely present.\n\n### Chi-Square Test Assumptions\n\n-   The levels of the variables are mutually exclusive.\n\n-   Each subject may contribute data to one and only one cell in the χ2.\n\n-   The study groups must be independent.\n\nIn addition to these, the Cochran's assumptions must also be met, which are:\n\n-   No cells with 0 counts\n\n-   At least 80% of the cells in our table have counts of 5 or higher\n\n-   The Expected counts in each cell of the table should be 5 or more\n\n## Conclusions\n\n11.7% of participants who reported never feeling down, depressed, or hopeless over the past 2 weeks had a period in their life where they drank 4 or more drinks of any alcoholic beverage almost every day.\n\nThe proportion of people who have a history of excessive drinking increases with the severity of the self reported symptoms of depression.\n\n36.8% of participants who felt down, depressed or hopeless nearly every day had a period in their life where they drank 4 or more drinks of any alcoholic beverage almost every day.\n\n**Among adults of ages 21-79 participating in NHANES 2017-18, individuals who have had a period of heavy drinking (described as having 4 or more alcoholic beverages daily) have a greater degree of association with symptoms of depression (how often has the participant been bothered by the following problems: feeling down, depressed, or hopeless) compared to individuals who have not had a period of heavy drinking. Stronger feelings of depression are associated more strongly with a history of having had a period of excessive drinking.**\n\n# Session Information\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessioninfo::session_info()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n─ Session info ───────────────────────────────────────────────────────────────\n setting  value\n version  R version 4.3.2 (2023-10-31 ucrt)\n os       Windows 11 x64 (build 22621)\n system   x86_64, mingw32\n ui       RTerm\n language (EN)\n collate  English_United States.utf8\n ctype    English_United States.utf8\n tz       America/New_York\n date     2024-01-08\n pandoc   3.1.1 @ C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)\n\n─ Packages ───────────────────────────────────────────────────────────────────\n package      * version    date (UTC) lib source\n backports      1.4.1      2021-12-13 [1] CRAN (R 4.3.1)\n base64enc      0.1-3      2015-07-28 [1] CRAN (R 4.3.1)\n bookdown       0.37       2023-12-01 [1] CRAN (R 4.3.2)\n boot           1.3-28.1   2022-11-22 [1] CRAN (R 4.3.2)\n broom        * 1.0.5      2023-06-09 [1] CRAN (R 4.3.2)\n cellranger     1.1.0      2016-07-27 [1] CRAN (R 4.3.2)\n checkmate      2.3.1      2023-12-04 [1] CRAN (R 4.3.2)\n class          7.3-22     2023-05-03 [2] CRAN (R 4.3.2)\n cli            3.6.1      2023-03-23 [1] CRAN (R 4.3.2)\n cluster        2.1.6      2023-12-01 [1] CRAN (R 4.3.2)\n cmprsk         2.2-11     2022-01-06 [1] CRAN (R 4.3.2)\n codetools      0.2-19     2023-02-01 [2] CRAN (R 4.3.2)\n coin           1.4-3      2023-09-27 [1] CRAN (R 4.3.2)\n colorspace     2.1-0      2023-01-23 [1] CRAN (R 4.3.2)\n commonmark     1.9.0      2023-03-17 [1] CRAN (R 4.3.2)\n data.table     1.14.10    2023-12-08 [1] CRAN (R 4.3.2)\n DescTools      0.99.52    2023-12-01 [1] CRAN (R 4.3.2)\n digest         0.6.33     2023-07-07 [1] CRAN (R 4.3.2)\n dplyr        * 1.1.4      2023-11-17 [1] CRAN (R 4.3.2)\n e1071          1.7-14     2023-12-06 [1] CRAN (R 4.3.2)\n Epi            2.47.1     2023-04-25 [1] CRAN (R 4.3.2)\n etm            1.1.1      2020-09-08 [1] CRAN (R 4.3.2)\n evaluate       0.23       2023-11-01 [1] CRAN (R 4.3.2)\n Exact          3.2        2022-09-25 [1] CRAN (R 4.3.1)\n expm           0.999-8    2023-11-29 [1] CRAN (R 4.3.2)\n fansi          1.0.6      2023-12-08 [1] CRAN (R 4.3.2)\n farver         2.1.1      2022-07-06 [1] CRAN (R 4.3.2)\n fastmap        1.1.1      2023-02-24 [1] CRAN (R 4.3.2)\n forcats      * 1.0.0      2023-01-29 [1] CRAN (R 4.3.2)\n foreign        0.8-86     2023-11-28 [1] CRAN (R 4.3.2)\n Formula        1.2-5      2023-02-24 [1] CRAN (R 4.3.1)\n generics       0.1.3      2022-07-05 [1] CRAN (R 4.3.2)\n ggformula    * 0.12.0     2023-11-09 [1] CRAN (R 4.3.2)\n ggplot2      * 3.4.4      2023-10-12 [1] CRAN (R 4.3.2)\n ggridges     * 0.5.5      2023-12-15 [1] CRAN (R 4.3.2)\n gld            2.6.6      2022-10-23 [1] CRAN (R 4.3.2)\n glue         * 1.6.2      2022-02-24 [1] CRAN (R 4.3.2)\n gridExtra      2.3        2017-09-09 [1] CRAN (R 4.3.2)\n gt           * 0.10.0     2023-10-07 [1] CRAN (R 4.3.2)\n gtable         0.3.4      2023-08-21 [1] CRAN (R 4.3.2)\n haven          2.5.4      2023-11-30 [1] CRAN (R 4.3.2)\n highr          0.10       2022-12-22 [1] CRAN (R 4.3.2)\n Hmisc          5.1-1      2023-09-12 [1] CRAN (R 4.3.2)\n hms            1.1.3      2023-03-21 [1] CRAN (R 4.3.2)\n htmlTable      2.4.2      2023-10-29 [1] CRAN (R 4.3.2)\n htmltools      0.5.7      2023-11-03 [1] CRAN (R 4.3.2)\n htmlwidgets    1.6.4      2023-12-06 [1] CRAN (R 4.3.2)\n httr           1.4.7      2023-08-15 [1] CRAN (R 4.3.2)\n janitor      * 2.2.0      2023-02-02 [1] CRAN (R 4.3.2)\n jsonlite       1.8.8      2023-12-04 [1] CRAN (R 4.3.2)\n kableExtra   * 1.3.4      2021-02-20 [1] CRAN (R 4.3.2)\n knitr        * 1.45       2023-10-30 [1] CRAN (R 4.3.2)\n labeling       0.4.3      2023-08-29 [1] CRAN (R 4.3.1)\n labelled       2.12.0     2023-06-21 [1] CRAN (R 4.3.2)\n lattice      * 0.22-5     2023-10-24 [1] CRAN (R 4.3.2)\n libcoin        1.0-10     2023-09-27 [1] CRAN (R 4.3.2)\n lifecycle      1.0.4      2023-11-07 [1] CRAN (R 4.3.2)\n lmom           3.0        2023-08-29 [1] CRAN (R 4.3.1)\n lmtest         0.9-40     2022-03-21 [1] CRAN (R 4.3.2)\n lubridate    * 1.9.3      2023-09-27 [1] CRAN (R 4.3.2)\n magrittr       2.0.3      2022-03-30 [1] CRAN (R 4.3.2)\n markdown       1.12       2023-12-06 [1] CRAN (R 4.3.2)\n MASS           7.3-60     2023-05-04 [1] CRAN (R 4.3.2)\n Matrix       * 1.6-4      2023-11-30 [1] CRAN (R 4.3.2)\n matrixStats    1.2.0      2023-12-11 [1] CRAN (R 4.3.2)\n mgcv           1.9-1      2023-12-21 [1] CRAN (R 4.3.2)\n modeltools     0.2-23     2020-03-05 [1] CRAN (R 4.3.1)\n mosaic         1.9.0      2023-11-10 [1] CRAN (R 4.3.2)\n mosaicCore     0.9.4.0    2023-11-05 [1] CRAN (R 4.3.2)\n mosaicData   * 0.20.4     2023-11-05 [1] CRAN (R 4.3.2)\n multcomp       1.4-25     2023-06-20 [1] CRAN (R 4.3.2)\n multcompView   0.1-9      2023-04-09 [1] CRAN (R 4.3.2)\n munsell        0.5.0      2018-06-12 [1] CRAN (R 4.3.2)\n mvtnorm        1.2-4      2023-11-27 [1] CRAN (R 4.3.2)\n naniar       * 1.0.0      2023-02-02 [1] CRAN (R 4.3.2)\n nhanesA      * 0.7.4      2023-07-16 [1] CRAN (R 4.3.2)\n nlme           3.1-164    2023-11-27 [1] CRAN (R 4.3.2)\n nnet           7.3-19     2023-05-03 [1] CRAN (R 4.3.2)\n nortest        1.0-4      2015-07-30 [1] CRAN (R 4.3.1)\n numDeriv       2016.8-1.1 2019-06-06 [1] CRAN (R 4.3.1)\n patchwork    * 1.1.3      2023-08-14 [1] CRAN (R 4.3.2)\n pillar         1.9.0      2023-03-22 [1] CRAN (R 4.3.2)\n pkgconfig      2.0.3      2019-09-22 [1] CRAN (R 4.3.2)\n plyr           1.8.9      2023-10-02 [1] CRAN (R 4.3.2)\n proxy          0.4-27     2022-06-09 [1] CRAN (R 4.3.2)\n purrr        * 1.0.2      2023-08-10 [1] CRAN (R 4.3.2)\n R6             2.5.1      2021-08-19 [1] CRAN (R 4.3.2)\n RColorBrewer   1.1-3      2022-04-03 [1] CRAN (R 4.3.1)\n rcompanion   * 2.4.34     2023-09-17 [1] CRAN (R 4.3.2)\n Rcpp           1.0.11     2023-07-06 [1] CRAN (R 4.3.2)\n readr        * 2.1.4      2023-02-10 [1] CRAN (R 4.3.2)\n readxl         1.4.3      2023-07-06 [1] CRAN (R 4.3.2)\n rlang          1.1.2      2023-11-04 [1] CRAN (R 4.3.2)\n rmarkdown      2.25       2023-09-18 [1] CRAN (R 4.3.2)\n rmdformats   * 1.0.4      2022-05-17 [1] CRAN (R 4.3.2)\n rootSolve      1.8.2.4    2023-09-21 [1] CRAN (R 4.3.1)\n rpart          4.1.23     2023-12-05 [1] CRAN (R 4.3.2)\n rstudioapi     0.15.0     2023-07-07 [1] CRAN (R 4.3.2)\n rvest          1.0.3      2022-08-19 [1] CRAN (R 4.3.2)\n sandwich       3.1-0      2023-12-11 [1] CRAN (R 4.3.2)\n sass           0.4.8      2023-12-06 [1] CRAN (R 4.3.2)\n scales         1.3.0      2023-11-28 [1] CRAN (R 4.3.2)\n sessioninfo    1.2.2      2021-12-06 [1] CRAN (R 4.3.2)\n snakecase      0.11.1     2023-08-27 [1] CRAN (R 4.3.2)\n stringi        1.8.3      2023-12-11 [1] CRAN (R 4.3.2)\n stringr      * 1.5.1      2023-11-14 [1] CRAN (R 4.3.2)\n survival       3.5-7      2023-08-14 [1] CRAN (R 4.3.2)\n svglite        2.1.3      2023-12-08 [1] CRAN (R 4.3.2)\n systemfonts    1.0.5      2023-10-09 [1] CRAN (R 4.3.2)\n TH.data        1.1-2      2023-04-17 [1] CRAN (R 4.3.2)\n tibble       * 3.2.1      2023-03-20 [1] CRAN (R 4.3.2)\n tidyr        * 1.3.0      2023-01-24 [1] CRAN (R 4.3.2)\n tidyselect     1.2.0      2022-10-10 [1] CRAN (R 4.3.2)\n tidyverse    * 2.0.0      2023-02-22 [1] CRAN (R 4.3.2)\n timechange     0.2.0      2023-01-11 [1] CRAN (R 4.3.2)\n tzdb           0.4.0      2023-05-12 [1] CRAN (R 4.3.2)\n utf8           1.2.4      2023-10-22 [1] CRAN (R 4.3.2)\n vctrs          0.6.5      2023-12-01 [1] CRAN (R 4.3.2)\n viridisLite    0.4.2      2023-05-02 [1] CRAN (R 4.3.2)\n visdat         0.6.0      2023-02-02 [1] CRAN (R 4.3.2)\n webshot        0.5.5      2023-06-26 [1] CRAN (R 4.3.2)\n withr          2.5.2      2023-10-30 [1] CRAN (R 4.3.2)\n xfun           0.41       2023-11-01 [1] CRAN (R 4.3.2)\n xml2           1.3.6      2023-12-04 [1] CRAN (R 4.3.2)\n yaml           2.3.7      2023-01-23 [1] CRAN (R 4.3.2)\n zoo            1.8-12     2023-04-13 [1] CRAN (R 4.3.2)\n\n [1] C:/Users/navee/AppData/Local/R/win-library/4.3\n [2] C:/Program Files/R/R-4.3.2/library\n\n──────────────────────────────────────────────────────────────────────────────\n```\n:::\n:::\n",
    "supporting": [
      "Study-1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\r\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}